---
- name: Prepare ONE Ubuntu base image
  hosts: "{{ lookup('env','HOSTS')  | default('all', true) }}"
  become: yes
  gather_facts: yes

  tasks:

    - name: Copy sysadmin's RSA public key
      authorized_key:
        user: sysadmin
        key: "{{ lookup('file', 'files/RSA/sysadmin_boe.pub') }}"

    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
          - resolvconf
          - ifupdown
        state: present
        update_cache: yes

    - name: Upgrade Ubuntu packages
      apt:
        upgrade: dist

    - name: Uninstall cloud-init to prevent conflics with one-context
      shell: apt-get purge -y cloud-init

    - name: Download one context package and install it
      get_url:
        url: https://github.com/OpenNebula/addon-context-linux/releases/download/v5.10.0/one-context_5.10.0-1.deb
        dest: /tmp/one-context_5.10.0-1.deb

    - name: Install one context instalar one context
      shell: dpkg -i /tmp/one-context_*deb || apt-get install -fy

    - name: Edit resolvconf interface order
      replace:
        path: /etc/resolvconf/interface-order
        regexp: 'br\|eth'
        replace: 'br|eth|en'
