---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6

  
  tasks:
    
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: present

    - name: Creates directory
      file:
        path: /root/hello
        state: directory    

    - name: descargar ONE contextualizacion
      get_url:
        url: https://github.com/OpenNebula/addon-context-linux/releases/download/v5.10.0/one-context_5.10.0-1.deb
        dest: /root/hello/one-context_5.10.0-1.deb

    - name: desinstalar could init
      shell: apt-get purge -y cloud-init

    - name: instalar one context
      shell: dpkg -i one-context_*deb || apt-get install -fy 
     
    

