---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6

  roles:
    - role: geerlingguy.nfs
  
  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: present

    - name: contectualizacion ONE
      command:
        argv:
          - wget https://github.com/OpenNebula/addon-context-linux/releases/download/v5.0.3/one-context_5.0.3.deb
          - dpkg -i one-context*deb
          - apt-get install ruby # only needed for onegate command
          - apt-get install -y cloud-utils